apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: {Plural}.{GroupName}
spec:
  group: {GroupName}
  names:
    kind: {Kind}
    listKind: {Kind}List
    plural: {Plural}
  scope: Namespaced
  version: {Version}
